<?php
/**
 * Layout
 * 
 * @package		Electronic Map
 * @subpackage	Application
 * @category    Layout
 * @version     1.0
 * @copyright   (c) 2014, Business Switch Pty Ltd
 * @author      Castro Paulo Jose <paulo.castro@business-switch.com.au>
 * @modified    11 November 2014
 * Default layout elements.
 */
?>

    <?php echo $this->partial('layout/el_header'); ?>  

    <?php echo $this->content;?>

    <?php echo $this->partial('layout/el_footer'); ?>  