<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'ELayout\Module'                     => __DIR__ . '/Module.php',
  'ELayout\Controller\IndexController' => __DIR__ . '/src/ELayout/Controller/IndexController.php',
);
